setwd("E:/Data/exploratory analysis/exdata-data-household_power_consumption/ExData_Plotting1")
data<- read.csv("twoday_data.csv",header=TRUE)
data[,1]<-as.Date(as.character(data$Date),"%d/%m/%Y",tz="UTC")
date_time<-as.character(paste(as.character(data$Date),as.character(data$Time)))
datetime<-strptime(date_time,"%Y-%m-%d %H:%M:%S",tz="UTC")
Sys.setlocale(category="LC_TIME",local="USA")
png(file="plot3.png", width = 480, height = 480, units = "px")
plot(datetime,data$Sub_metering_1,type="l",ylab="Energy Sub metering")

lines(datetime,data$Sub_metering_2,type="l",col="red")
lines(datetime,data$Sub_metering_3,type="l",col="blue")
legend("topright",legend=c("Sub_metering_1","Sub_metering_2","Sub_metering_3"),col=c("black","red","blue"),lty=c(1,1,1),xjust=1)
dev.off()
