setwd("E:/Data/exploratory analysis/exdata-data-household_power_consumption/ExData_Plotting1")
data<- read.csv("twoday_data.csv",header=TRUE)
data[,1]<-as.Date(as.character(data$Date),"%d/%m/%Y",tz="UTC")
date_time<-as.character(paste(as.character(data$Date),as.character(data$Time)))
datetime<-strptime(date_time,"%Y-%m-%d %H:%M:%S",tz="UTC")
Sys.setlocale(category="LC_TIME",local="USA")
png(file="plot4.png", width = 480, height = 480, units = "px")
par(mfrow=c(2,2),mar=c(4,4,4,4))
plot(datetime,data$Global_active_power,type="l",xlab="")
plot(datetime,data$Voltage,type="l",xlab="datetime")
plot(datetime,data$Sub_metering_1,type="l",xlab="",ylab="Energy sub metering")
lines(datetime,data$Sub_metering_2,type="l",col="red")
lines(datetime,data$Sub_metering_3,type="l",col="blue")
plot(datetime,data$Global_reactive_power,type="l",xlab="datetime")
dev.off()
